HW3 is completed
MyLi2tlePony/OtusGolang2022 pull request #3
Opened 2022-05-29 15:19 UTC by MyLi2tlePony

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-03 20:07 UTC, farir1408 requested changes

2022-06-03 20:07 UTC, farir1408 commented on hw03_frequency_analysis/top.go
> +	sortWords(&words)
Зачем эта сортировка?

2022-06-03 20:07 UTC, farir1408 commented on hw03_frequency_analysis/top.go
> +	for _, frequency := range wordsFrequency {
Сортировка внутри цикла - кажется с этим кодом что-то не так. Не очень понимаю зачем он нужен.

2022-06-03 20:07 UTC, farir1408 commented on hw03_frequency_analysis/top.go
> +	sort.Slice(topFrequencies, func(i, j int) bool {
Ещё одна сортировка

2022-06-03 20:11 UTC, farir1408 commented
Здравствуйте!

Сейчас алгоритм решения задачи максимально сложный и неочевидный. Давайте попробуем использовать такое решение: Строим слайс всех слов. Дальше строим паму слово-счётчик. С помощью полученной мапы строим слайс уникальных слов используя ключи вмапе. Дальше сортируем слайс уникальных слов используя функцию sort.Slice() и в функции сортировки используем замыкание на нашу мапу. Получим, что мы сортируем слайс уникальных слов используя счётчики из мапы. В итоге получаем отсортированный слайс уникальных слов, и нужно только взять срез на 10 элементов. Если у вас возникают сложности с данным решением, напишите мне в телеграм)

2022-06-18 09:52 UTC, farir1408 approved these changes

2022-06-18 09:53 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.
Отличная работа, принято 10/10
Согласитесь, такая реализация читается проще)

2022-06-18 10:00 UTC, MyLi2tlePony commented
> Здравствуйте!
> 
> Спасибо за выполнение домашнего задания. Отличная работа, принято 10/10 Согласитесь, такая реализация читается проще)

Да, так гораздо лучше, спасибо за ваш развернутый комментарий, очень помогли)

2022-06-18 10:05 UTC, merged